### ISSUE TITLE
questions about plotting.

### ISSUE THREAD

**Issue by pengzhangzhi** [guanyingc/python_plot_utils#1]
Prof. Chen, thanks so much for such a amazing tutorial. I have a question about the dpi. Sometimes I have to draw few `.png` picture with python and combine them in PPT for further beatifications.  But `.png` files are very blur. How should I make them as clear as the vector-format (I know it is impossible, I just want them can be clearly read in a paper). Increasing dpi is a good idea? How much ipi is enough to satisfy my need? Thanks for your time~

**Comment by guanyingc** [comment]
Hi, 
You can just save the image to pdf format.

I have just updated --format argument to pdf.
