### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by pengzhangzhi** [guanyingc/python_plot_utils#2]
Would you like to encapsulate this code into a python wrapper?  That would be much more convenient for plotting. Just like original plt but with much more pretty layout.

**Comment by pengzhangzhi** [comment]
Or If you have such plan, I would like to help you with that (Developing APIs)

**Comment by guanyingc** [comment]
Hi, thanks for your great suggestion! 

I have no plan to do that. But if you have time, you can create a new repo to develop it and release it. Then I can use your APIs as well. :-)
