### ISSUE TITLE
conf:format can't work

### ISSUE THREAD

**Issue by byerose** [guanyingc/python_plot_utils#4]
in `plot_diagram.py`
`parser.add_argument('--format', default='png', help='overwrite the save figure format, pdf|png|jpg')` will cause the format in the conf to fail.
should be
`parser.add_argument('--format', help='overwrite the save figure format, pdf|png|jpg')`

**Comment by guanyingc** [comment]
Hi, thanks for the bug report. Fix it in https://github.com/guanyingc/python_plot_utils/commit/d73b62ba7185db0c86b8ecb0c13fe23a7714cab5.
